services:
  rest-api:
    build:
      context: './'
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
    env_file: ./back/.env
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    networks:
      - backend
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kotlinDB

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
